linters-settings:
  govet:
    shadow: true
  maligned:
    suggest-new: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 300
  lll:
    line-length: 200
  golint:
    min-confidence: 0

issues:
  include:
    - EXC0002 # disable excluding of issues about comments from golint
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    # golint: Only require comments on methods
    - exported (const|var) .* should have comment.*
    - comment on exported (const|var) .* should be of the form
    - should have a package comment, unless it's in another file for this package

linters:
  enable-all: false
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - copyloopvar
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - gochecknoglobals

run:
  concurrency: 4
  deadline: 5m
