version: "3.7"
services: 
  influxdb:
    image: influxdb:1.8-alpine
    volumes: 
      - influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana:7.5.3
    volumes: 
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
  telegraf:
    build: .
    volumes: 
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./plugin-test.conf:/app/plugin.conf:ro
volumes: 
  influxdb:
  grafana: