version: "3.7"
services:
  influxdb:
    image: influxdb:2.1-alpine
    volumes:
      - influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
  telegraf:
    build: .
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./plugin.conf:/app/plugin.conf:ro
  deluge:
    image: ghcr.io/linuxserver/deluge
    ports:
      - 8112:8112
      - 58846
      - 58946
      - 58946/udp
    volumes:
      - deluge-config:/config
      - deluge-downloads:/downloads
volumes:
  influxdb:
  grafana:
  deluge-config:
  deluge-downloads:
